name = "Cousins"
author = "fnnln"
version = "v0.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e11fe527b152bb058f3decf14c429c8c9ca2a98a55127c26874584650abe4912"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
