name = "Cousins"
author = "fnnln"
version = "v0.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7888cc0f45c2086f080b3e002def0a53d4f468d95f7894a19ccd48683a4826a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
