name = "Cousins"
author = "fnnln"
version = "v0.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71293303e0e4012f865cbabf30dd8f639d7854da9b31c46bf07b7e864de12c5c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
